version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    command: npm run dev
    env_file:
      - .env.development

  postgresql:
    image: postgres:16
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: