service: ecr-lambda-api
frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  httpApi:
    cors: true
    payload: '2.0' 

functions:
  app:
    handler: dist/app.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: ANY

plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - 'dist/**'
