service: ecr-lambda-api
frameworkVersion: '^4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  httpApi:
    cors: true
    payload: '2.0' 

functions:
  app:
    name: ecr-lambda-api-dev-app
    image:
      uri: 780673962482.dkr.ecr.us-east-1.amazonaws.com/ecr-lambda-api:latest
    timeout: 30
    events:
      - httpApi:
          path: '/{proxy+}'
          method: ANY

plugins:
  - serverless-offline

package:
  patterns:
    - 'node_modules/**'
    - 'dist/**'
