openapi: 3.0.0
info:
  title: API REST Serverless
  version: 1.0.0
  description: Documentación generada en YAML para los endpoints de la API
servers:
  - url: http://localhost:3000
    description: Servidor local
  - url: https://{stage}.execute-api.{region}.amazonaws.com
    description: Servidor de producción
paths:
  /api/hello:
    get:
      summary: Devuelve un saludo
      description: Endpoint que retorna un mensaje de saludo.
      operationId: getHello
      responses:
        200:
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ¡Hola, mundo!
  /api/ping:
    get:
      summary: Verifica el estado del servidor
      description: Endpoint para comprobar si el servidor está activo.
      operationId: getPing
      responses:
        200:
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong
