name: Deploy to AWS ECR and Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Run tests
        run: |
          npm run test

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 780673962482.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t ecr-lambda-api .
          docker tag ecr-lambda-api:latest 780673962482.dkr.ecr.us-east-1.amazonaws.com/ecr-lambda-api:latest
          docker push 780673962482.dkr.ecr.us-east-1.amazonaws.com/ecr-lambda-api:latest

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ecr-lambda-api-dev-app \
            --image-uri 780673962482.dkr.ecr.us-east-1.amazonaws.com/ecr-lambda-api:latest


